version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "20:00"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - alma/squad-devx

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "20:00"
    groups:
      # Separate minor/patches updates from major updates, which will all have their own PR
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
