dist: bionic
language: python
cache: pip
install: pip install tox tox-travis
script: tox -v
python:
- 3.6
- 3.7
- 3.8
- 3.9-dev
jobs:
  fast_finish: true
  include:
  - python: 3.8
    env: TOXENV=flake8
  - name: "Code checks"
    if: type = pull_request
    dist: bionic
    language: python
    python: 3.8
    install: pip install pre-commit
    script:
      pre-commit run --all-files --show-diff-on-failure
