[tool.black]
line-length = 99
skip-numeric-underscore-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | tmp
  | .venv
)/
'''

[tool.isort]
force_grid_wrap = false
include_trailing_comma = true
line_length = 99
multi_line_output = 3
skip_glob = ''
use_parentheses = true
combine_as_imports = true
